//! Production cfg script files: the loader behind `exec <name>` /
//! `exec_configs` and the saver behind `writecfg`.
//!
//! Every cfg name resolves to at most two files, user first and project
//! overlay second (ADR 0013: `config.cfg`, `subagent.cfg`, `<agent>.cfg`,
//! and any user profile follow one layout):
//!
//! - `<profile config root>/<name>.cfg` — `~/.o2` by default,
//!   `~/.o2/profiles/<profile>` under `--profile`/`OMP_PROFILE`
//!   ([`omp_core::dirs::profile_config_dir`]);
//! - `<project>/.omp/<name>.cfg`.
//!
//! [`CfgFiles::load`] concatenates both texts so the project overlay runs
//! after the user script; [`CfgFiles::save`] always writes the user file
//! atomically (the project overlay is edited by `omp config set`).

use std::{
	fs, io,
	path::{Path, PathBuf},
};

use omp_con::{CfgLoader, CfgSaver, ConError, ConResult};
use omp_core::{Str, dirs::DataDirError};

/// Cfg script resolution for one process: user root plus optional project.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CfgFiles {
	user:    PathBuf,
	project: Option<PathBuf>,
}

impl CfgFiles {
	/// Resolves the user root for the selected profile and the project's
	/// `.omp` overlay directory.
	///
	/// # Errors
	///
	/// [`DataDirError::HomeUnset`] when no home directory is set.
	pub fn new(project_root: Option<&Path>) -> Result<Self, DataDirError> {
		let user = omp_core::dirs::user_config_root()?;
		Ok(Self::with_roots(user, project_root.map(|root| root.join(".omp"))))
	}

	/// Explicit roots (tests, migration into a scratch directory).
	#[must_use]
	pub const fn with_roots(user: PathBuf, project: Option<PathBuf>) -> Self {
		Self { user, project }
	}

	/// The user (profile) root every save lands in.
	#[must_use]
	pub fn user_root(&self) -> &Path {
		&self.user
	}

	/// The project overlay directory (`<project>/.omp`), when present.
	#[must_use]
	pub fn project_root(&self) -> Option<&Path> {
		self.project.as_deref()
	}

	/// User-file path for a cfg name (`config` and `config.cfg` are the same
	/// file).
	#[must_use]
	pub fn user_path(&self, name: &str) -> PathBuf {
		self.user.join(file_name(name))
	}

	/// Project-overlay path for a cfg name, when a project is attached.
	#[must_use]
	pub fn project_path(&self, name: &str) -> Option<PathBuf> {
		self.project.as_ref().map(|root| root.join(file_name(name)))
	}

	/// Concatenated user-then-project script text, `None` when neither
	/// file exists. A generated header from an older build is normalized.
	#[must_use]
	pub fn load(&self, name: &str) -> Option<Str> {
		let mut script = String::new();
		for path in std::iter::once(self.user_path(name)).chain(self.project_path(name)) {
			let Ok(text) = fs::read_to_string(&path) else {
				continue;
			};
			if !script.is_empty() && !script.ends_with('\n') {
				script.push('\n');
			}
			script.push_str(&migrate_generated_preamble(&text));
		}
		(!script.is_empty()).then(|| Str::new(script))
	}

	/// Writes `contents` to the user file for `name` atomically (temporary
	/// file plus rename), creating the root as needed.
	///
	/// # Errors
	///
	/// Any filesystem failure, as an [`io::Error`].
	pub fn save(&self, name: &str, contents: &str) -> io::Result<()> {
		let path = self.user_path(name);
		if let Some(parent) = path.parent() {
			fs::create_dir_all(parent)?;
		}
		let temporary = path.with_extension(format!("cfg.tmp.{}", std::process::id()));
		fs::write(&temporary, contents.as_bytes())?;
		fs::rename(&temporary, &path).inspect_err(|_| {
			let _ = fs::remove_file(&temporary);
		})
	}
}

impl CfgLoader for CfgFiles {
	fn load(&self, name: &str) -> Option<Str> {
		Self::load(self, name)
	}
}

impl CfgSaver for CfgFiles {
	fn save(&self, name: &str, contents: &str) -> ConResult<()> {
		Self::save(self, name, contents).map_err(|error| ConError::Usage(Str::new(error.to_string())))
	}
}

/// `<name>.cfg`, tolerating an explicit `.cfg` suffix.
fn file_name(name: &str) -> String {
	format!("{}.cfg", name.trim_end_matches(".cfg"))
}

/// Drops the bare `unbindall` reset that the pre-baseline `dump` wrote at the
/// top of every generated cfg. It was a serializer preamble, never a user's
/// intent, and with defaults now seeded from the default bind cfg it would
/// erase them. A hand-written `unbindall` followed by `bind` lines is kept.
#[must_use]
pub fn migrate_generated_preamble(script: &str) -> String {
	let generated = script
		.lines()
		.next()
		.is_some_and(|line| line.starts_with("// generated by omp-con dump"));
	if !generated {
		return script.to_owned();
	}
	let mut lines = script.lines().peekable();
	let mut out = String::with_capacity(script.len());
	while let Some(line) = lines.next() {
		if line.trim() == "unbindall"
			&& !lines
				.peek()
				.is_some_and(|next| next.trim_start().starts_with("bind "))
		{
			continue;
		}
		out.push_str(line);
		out.push('\n');
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn names_resolve_to_user_then_project_files_and_concatenate() {
		let dir = tempfile::tempdir().unwrap();
		let user = dir.path().join("o2");
		let project = dir.path().join("proj/.omp");
		fs::create_dir_all(&user).unwrap();
		fs::create_dir_all(&project).unwrap();
		let files = CfgFiles::with_roots(user.clone(), Some(project.clone()));
		assert_eq!(files.user_path("config"), user.join("config.cfg"));
		assert_eq!(files.user_path("sonic.cfg"), user.join("sonic.cfg"));
		assert_eq!(files.project_path("subagent"), Some(project.join("subagent.cfg")));
		assert_eq!(files.load("subagent"), None);
		fs::write(user.join("subagent.cfg"), "ai_fastmode 0").unwrap();
		assert_eq!(files.load("subagent").unwrap().as_str(), "ai_fastmode 0");
		fs::write(project.join("subagent.cfg"), "ai_thinking low\n").unwrap();
		assert_eq!(files.load("subagent.cfg").unwrap().as_str(), "ai_fastmode 0\nai_thinking low\n");
	}

	/// The subagent spawn path installs [`CfgFiles`] as its loader (kernel
	/// `TaskSessionTool`), so `~/.o2/subagent.cfg` and `~/.o2/<agent>.cfg`
	/// reach every child in ADR 0013 order — user script, project overlay,
	/// then the agent class — with `config.cfg` never re-read over the seed.
	#[test]
	fn spawn_configs_run_user_then_project_subagent_and_agent_cfgs() {
		let dir = tempfile::tempdir().unwrap();
		let user = dir.path().join("o2");
		let project = dir.path().join("proj/.omp");
		fs::create_dir_all(&user).unwrap();
		fs::create_dir_all(&project).unwrap();
		fs::write(user.join("config.cfg"), "ai_fastmode 1\nai_thinking low\n").unwrap();
		fs::write(user.join("subagent.cfg"), "ai_fastmode 0\nai_thinking medium\n").unwrap();
		fs::write(project.join("subagent.cfg"), "ai_thinking high\n").unwrap();
		fs::write(user.join("scout.cfg"), "ai_model @smol\n").unwrap();
		let files = CfgFiles::with_roots(user, Some(project));
		let child = omp_con::Ctx::new();
		omp_con::AI_FASTMODE.set(&child, true).unwrap();
		let outcome = child.exec_spawn_configs(&files, "scout");
		assert_eq!(outcome.failed, 0);
		assert!(!omp_con::AI_FASTMODE.get(&child), "user subagent.cfg ran");
		assert_eq!(omp_con::AI_THINKING.get(&child).as_str(), "high", "project overlay ran last");
		assert_eq!(omp_con::AI_MODEL.get(&child).as_str(), "@smol", "user <agent>.cfg ran");
	}

	#[test]
	fn save_writes_the_user_file_atomically_and_creates_the_root() {
		let dir = tempfile::tempdir().unwrap();
		let user = dir.path().join("missing/o2");
		let files = CfgFiles::with_roots(user.clone(), None);
		CfgSaver::save(&files, "profile", "ai_model @smol\n").unwrap();
		assert_eq!(fs::read_to_string(user.join("profile.cfg")).unwrap(), "ai_model @smol\n");
		assert!(fs::read_dir(&user).unwrap().all(|entry| {
			!entry
				.unwrap()
				.file_name()
				.to_string_lossy()
				.contains(".tmp.")
		}));
		assert_eq!(files.load("profile").unwrap().as_str(), "ai_model @smol\n");
	}
}
